### ISSUE TITLE
Members permissions default

### ISSUE THREAD

**Issue by aldldl** [explosivegaming/scenario#102]
**Factorio version**
Version number: 0.17*

**Scenario version**
Version number: 5.0

**Bug description**
Member should be able to edit queue for research.

**Reproduction method**
4. See error in log

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Cooldude2606** [comment]
Fixed in [v5.7.0](https://github.com/explosivegaming/scenario/releases/tag/5.7.0)
