### ISSUE TITLE
Rank changes over time when already have a higher rank

### ISSUE THREAD

**Issue by JesseyWhite** [explosivegaming/scenario#103]
**Factorio version**
Version number: 0.17

**Scenario version**
Version number: 2019-06-06

**Bug description**
When you have any rank higher than regular, you will be demoted over time because the timer promotion does not check if your rank is higher than regular and automatically demotes you what would normally be a promotion for a guest.

Bug also happens when the timer for a regular would be promoted to a vet.

**Reproduction method**
1. Have a rank higher than regular
2. Wait the same time a guest has to for them to be promoted to regular.

**Expected behavior**
When you already have a higher rank, you should not be demoted.

**Screenshots**
https://i.imgur.com/QE15bC6.png

**Comment by Cooldude2606** [comment]
You arent demoted you are simply assigned to that role, Since you are able to have more than one role you retain your higher role as well as any more which are given. If it is removing roles then that would be an issue but from what you described it isnted removing your other roles.

**Comment by JesseyWhite** [comment]
The very first time this happened to me, it did demote me and could no longer decon. it was back when discord ranks were not synced yet. I assumed that it happened again so I made this bug report.
