### ISSUE TITLE
when clicking on title of warp, map view will snap to that warp's location

### ISSUE THREAD

**Issue by JesseyWhite** [explosivegaming/scenario#107]
**Feature overview**
Name: Click warp name to view location

**Details**
When clicking the name of a warp, regardless if standing on warp pad or not, player view should go to that location. 

**Possible methods**
The same mechanic is already used when clicking on a player's name in the player list.

**Additional context**
https://i.imgur.com/8iJUTMm.png

**Comment by Cooldude2606** [comment]
Added in [v5.7.1](https://github.com/explosivegaming/scenario/commit/271a84dcc0d3ad4e6358d20fedbb7acf2ed7faac)
