### ISSUE TITLE
2 chat commands not working

### ISSUE THREAD

**Issue by CmonMate497** [explosivegaming/scenario#111]
**Factorio version**
Version number: 0.17.53

**Scenario version**
Version number: V5.8

**Bug description**
rhd/lhd and redmew chat command responds with Unknown key

**Reproduction method**
1. Launch Factorio
2. Go onto an ExpGaming server or launch scenario in single player
3. Type in rhd, lhd and redmew
4. See error in log

**Expected behavior**
To respond with something like for lhd, "Trains Must be in LHD"

**Additional context**
Probably not high priority but thought I'd point it out

**Comment by Cooldude2606** [comment]
See pull request #112
