### ISSUE TITLE
MOAR LOGS

### ISSUE THREAD

**Issue by Rewish497** [explosivegaming/scenario#116]
**Feature overview**
Name: Logs for mining/destroying entities
TL;DR: ^^

**Details**
A log for mods/admins showing that a player has mined an entity, can be useful when a player has griefed (eg removing water pumps for power)

**Possible methods**

**Additional context**
https://nvfs.se/ul/rI6rJ.gif Something like this

**Comment by bbassie** [comment]
@CmonMate497 Gif is not available anymore 404 http error

**Comment by bbassie** [comment]
Will not implement because of performance reasons.

@Cooldude2606 please close this issue

**Comment by Cooldude2606** [comment]
A log file was added in #224 which allows admins / bots to access the logs. However an ingame method is still not implemented and deemed to be two preformance intensive without finding another solution. If a new solution is found it can become its own feature request.
