### ISSUE TITLE
More warp stuff not working

### ISSUE THREAD

**Issue by CmonMate497** [explosivegaming/scenario#123]
**Factorio version**
Version number: 0.17.64

**Scenario version**
Version number: V5.9

**Bug description**
![Discord_7bn1OIHMH1](https://user-images.githubusercontent.com/48069760/62821197-103e7680-bb69-11e9-9b24-a806413dcd50.png)

**Reproduction method**
1. Should say in Screenshot, I have no idea myself

**Expected behavior**
Warp stuff working properly ;)

**Comment by CmonMate497** [comment]
Previously, a lot of warp related issues have happened kinda similar to this (eg #121 and https://discordapp.com/channels/260843215836545025/343846445725515777/605038997055733760 onwards. Perhaps have a look in the script and see what might be causing this so we don't have issues relating to this again :D

**Comment by Cooldude2606** [comment]
Fixed two issues:
[Fixed multiple spawn warps being created ](https://github.com/explosivegaming/scenario/commit/792dcc03307431dcce3e65da70d762ff84e61016)
[Fixed warp creation](https://github.com/explosivegaming/scenario/commit/a7e6f155ae219162eb92a736dcb65f59c3075215)
