### ISSUE TITLE
Death Marker problems for Admins (maybe others)

### ISSUE THREAD

**Issue by flbuddymooreiv** [explosivegaming/scenario#125]
**Factorio version**
Version number: 0.17.66

**Scenario version**
Version number: S3 2019-08-18

**Bug description**
When dying, admin body turns to "Character Corpse" and immediately respawns - there is no way to mark where you died and the corpse turns to generic orange and not your actual player color. If you're looking for your player color, you will fail to find your corpse.

**Reproduction method**
1. Join
2. Die
3. Cry now that your populated armor is in an ocean of corpses in which you'll never find it.

**Expected behavior**
"Player died at HH:MM:SS" located on death coordinates

**Comment by Cooldude2606** [comment]
Fixed in [v5.9.1](https://github.com/explosivegaming/scenario/commit/30d63427d76c9755d7e7d2861504f936bf327c9f)
[Fixed instant respawn and death markers ](https://github.com/explosivegaming/scenario/commit/db102a79ff2793e867c11b2c1e0f95c30d42b54b)
