### ISSUE TITLE
Fix spelling in warp edit UI

### ISSUE THREAD

**Issue by flbuddymooreiv** [explosivegaming/scenario#131]
https://github.com/explosivegaming/scenario/blob/ab869bf5e80e8c46278948c651b125899929a34d/docs/control/Warps.html#L339

**Comment by Cooldude2606** [comment]
If you want to help with the docs you can download ldoc and then edit the doc strings inside the files. I will keep this in mind before I push the next release.
https://github.com/explosivegaming/scenario/blob/64bac536ef109137d2e2bc6b518517951de85a52/modules/control/warps.lua#L282

**Comment by Cooldude2606** [comment]
Fixed in [v5.10.0](https://github.com/explosivegaming/scenario/releases/tag/5.10.0)
See [commit](https://github.com/explosivegaming/scenario/commit/06030ff2c2c80e0b6f2302eb46f0eb419ace9366)
