### ISSUE TITLE
The Warp CRUD code needs some optimization for long-running games

### ISSUE THREAD

**Issue by flbuddymooreiv** [explosivegaming/scenario#132]
https://github.com/explosivegaming/scenario/blob/30d63427d76c9755d7e7d2861504f936bf327c9f/modules/gui/warp-list.lua#L439

This iteration causes the entire server to hang for multiple seconds on any warp CRUD methods once the player count has grown into the hundreds. I wish I could propose a solution but I'm not sure what one might be off the top of my head. I'm assuming every player's UI is their own UI so there is not some kind of shared UI that can be updated for all players to use.

**Comment by Cooldude2606** [comment]
I had thought about checking if a player is online or not and then always updating the gui when the player joins but decided to just have a simple solution for now to make sure everything else is working as intented. Thanks for the report will keep this in mind when the gui is next changed; planing a gui re work soon.

**Comment by Cooldude2606** [comment]
Fixed in [v5.10.0](https://github.com/explosivegaming/scenario/releases/tag/5.10.0)
See [commit](https://github.com/explosivegaming/scenario/commit/3a04e72b0cb20eee896a455c8cb7e927365c2741)
