### ISSUE TITLE
Mentioned notificaion treats usenames as regular expressions

### ISSUE THREAD

**Issue by ariscop** [explosivegaming/scenario#133]
**Reproduction method**
Observed with the name 'g-h-o-s-t', matched any message with a `t`

**Additional context**
https://github.com/explosivegaming/scenario/blob/7e06bfea133dd02838324f09c4d8764ec7596d50/modules/addons/chat-popups.lua#L31
Should be changed to
```if search_string:find(mentioned_player.name:lower(), 1, true) then```

Lua manual: https://www.lua.org/manual/5.2/manual.html#pdf-string.find

**Comment by Cooldude2606** [comment]
Fixed in PR #142 Fixed chat popup for players with - in name
