### ISSUE TITLE
Auto fill/ Fill4Me

### ISSUE THREAD

**Issue by bbassie** [explosivegaming/scenario#153]
**Feature overview**
Name: Auto Fill
A Fill4Me mod clone to the scenario? Maybe donator only? 🤑

**Details**
https://mods.factorio.com/mod/Fill4Me

https://i.imgur.com/YTbAsKL.gif

**Comment by tovernaar123** [comment]
i have been making this but rn bussy with factorio olympics so after that ill make sure its added

**Comment by bbassie** [comment]
Created Pull Request to add this:
Added Autofill toolbar button #175

**Comment by Cooldude2606** [comment]
Pull request implementing this feature has been merged into dev. Clossing issue.
