### ISSUE TITLE
clear inv on ban

### ISSUE THREAD

**Issue by tovernaar123** [explosivegaming/scenario#155]
**Feature overview**
Name: name-here
TL;DR: a few words about what the feature is
clear inventory of player on when banned
**Details**
A detailed description of what the new feature is.
nothing to explain XD
**Possible methods**
Any ideas you have had about how to implement the feature or any problems that may arise.

**Additional context**

**Comment by kevintayloruk** [comment]
Just wondering why you'd need to do this?

**Comment by tovernaar123** [comment]
i dont really know one of the mods asked me to put this on he did not have git :)

**Comment by tovernaar123** [comment]
@kevintayloruk i asked him he says that he would like it if the items of the banned player are put in a chest at spawn so other players can still use the items eg. if its a greefer that took the silo you dont lose it

**Comment by kevintayloruk** [comment]
It's the detail of putting it in a chest that helps!  I'll take a crack at it.

**Comment by tovernaar123** [comment]
ill close this after the pr has been merged

**Comment by Cooldude2606** [comment]
The current issue with the suggested solution is that it only effects bans through the player list. I think it would be best if a new module was made which listened to the events on_player_banned and on_player_kicked. This would be a very small module but it would solve the issue quite nicely.

**Comment by Cooldude2606** [comment]
Feature has been added in [6.0.5](https://github.com/explosivegaming/scenario/commit/9135608031e2f322a43aaa0375dc3609314fb76d) as a bug fix.
