### ISSUE TITLE
Decon trees and rocks if you drive into them.

### ISSUE THREAD

**Issue by Cooldude2606** [explosivegaming/scenario#162]
**Feature overview**
Name: Crash Decon
TL;DR: when you are in a car and you hit a tree or a rock then it mark it to be deconstructed, option to have this be turned off and on.

**Details**
Idea from: https://forums.factorio.com/viewtopic.php?f=33&t=85223

**Possible methods**
Use of on_entity_damaged and then test if the player is in a car and filter for trees and rocks. Then just mark them to be deconstructed. Using a command or gui to toggle would also be possible.

**Comment by oof2win2** [comment]
Same thread has code that would work.
```lua
script.on_event(defines.events.on_entity_damaged, function(event)
	local entity = event.entity
	local force = event.force
	if entity.type == "tree" and event.damage_type.name == "impact" and force then
		entity.order_deconstruction(force)
	end
end)
```

**Comment by PHIDIAS0303** [comment]
this should be done now
