### ISSUE TITLE
Issue loading default files

### ISSUE THREAD

**Issue by mlopezfm** [explosivegaming/scenario#168]
Describe the bug
Error log included below, permission_groups.lua and roles.lua have an issue

To Reproduce

    Start new server
    or
    Server reset automatically
    No admins or ranks

2.695 Script @/opt/factorio/temp/currently-playing/control.lua:30: [INFO] Loading file 43/ 48 (modules.commands.debug)
2.698 Script @/opt/factorio/temp/currently-playing/control.lua:30: [INFO] Loading file 44/ 48 (config.expcore.command_auth_admin)
2.698 Script @/opt/factorio/temp/currently-playing/control.lua:30: [INFO] Loading file 45/ 48 (config.expcore.command_auth_roles)
2.698 Script @/opt/factorio/temp/currently-playing/control.lua:30: [INFO] Loading file 46/ 48 (config.expcore.command_runtime_disable)
2.698 Script @/opt/factorio/temp/currently-playing/control.lua:30: [INFO] Loading file 47/ 48 (config.expcore.permission_groups)
2.698 Script @/opt/factorio/temp/currently-playing/control.lua:36: [ERROR] Failed to load file: config.expcore.permission_groups

2.698 Script @/opt/factorio/temp/currently-playing/control.lua:30: [INFO] Loading file 48/ 48 (config.expcore.roles)
2.699 Script @/opt/factorio/temp/currently-playing/control.lua:36: [ERROR] Failed to load file: config.expcore.roles

2.699 Script @/opt/factorio/temp/currently-playing/control.lua:47: [INFO] Require Overright! No more requires can be made!
2.699 Script @/opt/factorio/temp/currently-playing/control.lua:51: [INFO] All files loaded with 2 errors:
2.699 Script @/opt/factorio/temp/currently-playing/control.lua:52: [ERROR] config.expcore.permission_groups :: ...rio/temp/currently-playing/expcore/permission_groups.lua:153: table index is nil

stack traceback:
...rio/temp/currently-playing/expcore/permission_groups.lua:153: in function 'set_action'
...rio/temp/currently-playing/expcore/permission_groups.lua:196: in function 'disallow'
...p/currently-playing/config/expcore/permission_groups.lua:67: in main chunk
[C]: in function '_G.require'
[C]: in function 'pcall'
/opt/factorio/temp/currently-playing/control.lua:31: in main chunk
2.699 Script @/opt/factorio/temp/currently-playing/control.lua:52: [ERROR] config.expcore.roles :: ...factorio/temp/currently-playing/config/expcore/roles.lua:232: attempt to index a nil value

stack traceback:
...factorio/temp/currently-playing/config/expcore/roles.lua:232: in main chunk
[C]: in function '_G.require'
[C]: in function 'pcall'
/opt/factorio/temp/currently-playing/control.lua:31: in main chunk
2.699 Script @/opt/factorio/temp/currently-playing/control.lua:53: [END] -----| Explosive Gaming Scenario Loader |-----
2.699 Checksum for script /opt/factorio/temp/currently-playing/control.lua: 2879224307

**Comment by Cooldude2606** [comment]
Which branch of our scenario are you usings, and what version of factorio are you running this on?

**Comment by mlopezfm** [comment]
Factorio 0.17.79 (build 47865, linux64, headless), and i pulled from master.

Im running this headless through docker if that helps at all

**Comment by Cooldude2606** [comment]
Our master branch is designed to be ran with factorio 0.18 in preperation for version 1 release. Although we also run 0.17 servers which use the back ported scenario which can be found on [release/6.0.0-f.17](https://github.com/explosivegaming/scenario/releases/tag/6.0.0-f.17). Please try this branch and let me know if you still have the issue.

**Comment by mlopezfm** [comment]
wow big oopsie on my part! ill try the older branch, thanks!!
