### ISSUE TITLE
Toolbar blueprint book bad state

### ISSUE THREAD

**Issue by bbassie** [explosivegaming/scenario#178]
**Scenario version**
Version number: Current master

**Bug description**
When you've got a blueprint book in the toolbar and do /save-toolbar and then rejoin the toolbar wil be in a bad state:
![image](https://user-images.githubusercontent.com/17990055/97792350-33759b80-1bdd-11eb-9d6d-66815039b32f.png)

**Comment by bbassie** [comment]
Originally noticed by stugel2012 https://discordapp.com/channels/260843215836545025/440081765109989386/772246503359643668

**Comment by bbassie** [comment]
Doesn't look doable after all because [LuaPlayer.get_quick_bar_slot](https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.get_quick_bar_slot) returns an [LuaItemPrototype](https://lua-api.factorio.com/latest/LuaItemPrototype.html) that does only refer to the prototype of the item.

Possible side fix is to filter out the blueprints?

**Comment by Cooldude2606** [comment]
Due to the inablity to export blueprint data and the unlikelyhood of this ever being added, I consider #179 to be an acceptable mitigation for this issue.
