### ISSUE TITLE
Editing warps bug

### ISSUE THREAD

**Issue by bbassie** [explosivegaming/scenario#189]
**Factorio version**
Version number: 1.0.0

**Scenario version**
Version number: 6.1

**Bug description**
When editing a warp or after confirmed / canceled the action all warps are enabled whether or not you are actually able to.

**Expected behavior**
Enabled state not changing on edit

**Comment by Cooldude2606** [comment]
This should have been fixed by pr #190 but will need to confirm this.

**Comment by Cooldude2606** [comment]
I have now confirmed that this bug is fixed following the merge of the pr.
