### ISSUE TITLE
Quick inventory check

### ISSUE THREAD

**Issue by PHIDIAS0303** [explosivegaming/scenario#193]
If a moderator is not online when user grief, it sometimes can be hard to trace.
As there can be a lot of users that join and leave without doing anything.

Instead of /admin to get the user list and /o their inventory one by one.
If we can have a command that quickly filters out those users that only have 'welcome gift', 
or say those have a lot of ores on them, 
it would make tracing a lot easier.

For example, we can just test for the 20 last users,
(or until the first 'trusted' member online, as they may make a report if they see such things.)
and then output a list as a result.

However, the output list can be a bit long sometimes, 
so may need to integrate with the bot,
to display an output that is easier to read.

**Comment by Cooldude2606** [comment]
This feature was implemented in #206
Closing this request.
