### ISSUE TITLE
Ping last location of player

### ISSUE THREAD

**Issue by 7h3w1z4rd** [explosivegaming/scenario#197]
**Feature overview**
Name: Ping last location of player
TL;DR: Command that gps pings last location of specific player

**Details**
Command that would ping the position of the specific player provided in the command execution. Would provide the position of the player via a gps ping in the game chat. The ping itself would only be visible to the player who executed the command.

**Possible methods**
Get player via game.player list and fetch their position.

**Comment by Cooldude2606** [comment]
PR implementing this request has been merged into dev. Clossing issue.
