### ISSUE TITLE
Language identifier for moderation tools

### ISSUE THREAD

**Issue by DrahcPro** [explosivegaming/scenario#243]
**Feature overview**
Name: Language detection
Detect what language the player has their game in.

**Details**
Detect the language the player has their game set to.
Put this in the player overview posted to discord and if possible in factorio.

**Possible methods**
Use a [LocalisedString](https://lua-api.factorio.com/latest/Concepts.html#LocalisedString) like `local_language` in locale/\<language> set to the English name of the language it is said to. And request this with [request_string("local_language")](https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.request_translation) to get their language and put this in the right place.

E.g. have in `locale/nl` the file `language.cfg` set to this:
```
[language]
local-language=Dutch (Netherlands)
```

For ease of use also a list of all the locale with their language:
https://stackoverflow.com/a/28357857

**Additional context**
If you need help generating all the folders I'm open to help

**Comment by Cooldude2606** [comment]
Feature implimented via #244
