### ISSUE TITLE
Player list button unavailable

### ISSUE THREAD

**Issue by TiBarification** [explosivegaming/scenario#269]
**Factorio version**
Version number: 1.1.101

**Scenario version**
Version number: using dev branch

**Bug description**
...iles/temp/currently-playing/modules/gui/surveillance.lua:158: in function <...iles/temp/currently-playing/modules/gui/surveillance.lua:152>
        [C]: in function 'xpcall'
        .../serverfiles/temp/currently-playing/utils/event_core.lua:32: in function 'call_handlers'
        .../serverfiles/temp/currently-playing/utils/event_core.lua:39: in function <.../serverfiles/temp/currently-playing/utils/event_core.lua:37>
2324.242 Script @/data/serverfiles/temp/currently-playing/utils/event_core.lua:21: 
        ...iles/temp/currently-playing/modules/gui/surveillance.lua:158: attempt to index local 'frame' (a nil value)
stack traceback:
        .../serverfiles/temp/currently-playing/utils/event_core.lua:21: in function '__index'
        ...iles/temp/currently-playing/modules/gui/surveillance.lua:158: in function <...iles/temp/currently-playing/modules/gui/surveillance.lua:152>
        [C]: in function 'xpcall'
        .../serverfiles/temp/currently-playing/utils/event_core.lua:32: in function 'call_handlers'
        .../serverfiles/temp/currently-playing/utils/event_core.lua:39: in function <.../serverfiles/temp/currently-playing/utils/event_core.lua:37>
2324.258 Script @/data/serverfiles/temp/currently-playing/utils/event_core.lua:21: 
        ...iles/temp/currently-playing/modules/gui/surveillance.lua:158: attempt to index local 'frame' (a nil value)
stack traceback:
        .../serverfiles/temp/currently-playing/utils/event_core.lua:21: in function '__index'
        ...iles/temp/currently-playing/modules/gui/surveillance.lua:158: in function <...iles/temp/currently-playing/modules/gui/surveillance.lua:152>
        [C]: in function 'xpcall'

**Reproduction method**
1. Click on player list button
2. See error in console

**Expected behavior**
No error

**Comment by Cooldude2606** [comment]
I expect this to be resolved by the merge of #268 if not then I will investigate this further.
