### ISSUE TITLE
/set-trains-to-automatic not working for admin

### ISSUE THREAD

**Issue by DrahcPro** [explosivegaming/scenario#289]
**Factorio version**
Version number: 1.1.104

**Scenario version**
Version number: latest

**Bug description**
/set-trains-to-automatic gives the unauthorized error for me as admin

**Reproduction method**
1. Be admin
2. /set-trains-to-automatic

**Expected behavior**
![image](https://github.com/explosivegaming/scenario/assets/37268586/a335ec26-5e3f-4075-b0a5-b1b329b1f986)

**Comment by PHIDIAS0303** [comment]
#274
