### ISSUE TITLE
Add /tp command back

### ISSUE THREAD

**Issue by XenoCyber88** [explosivegaming/scenario#58]
The new teleport commands are overly complicated and require you to remember two separate commands. 

please re-add the /tp command for power users mods so they can quickly simply teleport to other users 

/tp from to

**Comment by Cooldude2606** [comment]
"overly complicated" /go-tp \<name\> or /bring \<name\> 
![NOTP](https://cdn.discordapp.com/emojis/447484775616348170.png?v=1)

**Comment by sakamakj** [comment]
I agree with Cooldude2606. /go-to player and /bring player works really well and if you change that it will take longer time for me instead.  It is really fast when using tab-completion and nowadays you can also use the /set-home command before you use it so that you can return after investigating the potential trouble.

**Comment by wsfjm** [comment]
I think too many vocabularies do not have localized files.
I'm sorry I can't read English at all. Only with translation software!

**Comment by Cooldude2606** [comment]
> do not have localized files

We understand that problem but out side the ones already done we have not had any one willing to add more to it. wsfjm if you wish to add your first language to it then it is fine by me.
See: https://help.github.com/articles/creating-a-pull-request/

**Comment by wsfjm** [comment]
I will not, Creating a pull request，https://github.com/wsfjm/explosivegaming-main/tree/master/locale/zh-CN[](url)
Not enough vocabulary

**Comment by JCA122204** [comment]
Mabye bring /tp back and leave the others, so that all 3 are available?

**Comment by XenoCyber88** [comment]
That had always been my request not to move one for the other but have all
coexist

**Comment by Cooldude2606** [comment]
Please see: #67
