### ISSUE TITLE
Escape should be abbreviated "Esc" and not "Ecs"

### ISSUE THREAD

**Issue by flbuddymooreiv** [explosivegaming/scenario#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Other information (please complete the following information):**
 - OS: [e.g. iOS, Windows, Linux]
 - Factorio Version: [e.g. 0.16.30]

**Additional context**

**Comment by Cooldude2606** [comment]
We need more context... where is this, which gui, is it in mutliple places, is it in all translations... etc...

**Comment by flbuddymooreiv** [comment]
My apologies. It appeared that when I created the issue it was against a
specific line of code. I will update asap but for what it's worth you can
search for "ecs" and it will be the only occurrence.

On Jun 27, 2018 6:28 AM, "Cooldude2606" <notifications@github.com> wrote:

We need more context... where is this, which gui, is it in mutliple places,
is it in all translations... etc...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/explosivegaming/scenario/issues/73#issuecomment-400622854>,
or mute the thread

**Comment by flbuddymooreiv** [comment]
Here is a permalink to the line at hand:

https://github.com/explosivegaming/scenario/blob/b41bee6e92a03314fe4ad04b2a4e25e5ce19b74f/ExpCore/sync.lua#L347

**Comment by JCA122204** [comment]
Someone close this. It has been fixed

**Comment by Cooldude2606** [comment]
I dont know how the assignees works but im sure there is a way to get my attion on github, but ill close this now. See pull request #74.
