### ISSUE TITLE
/repair doesn't place ghost entities

### ISSUE THREAD

**Issue by badgamernl** [explosivegaming/scenario#75]
**Describe the bug**
When running `/repair` it doesn't place ghost entities.

**To Reproduce**
1. Run command `/repair`
2. Only entities get repaired

**Expected behavior**
Expected to place ghost entities.

**Screenshots**
http://i.imgur.com/k5ZmGAX.gif

**Other information:**
 - OS: Windows
 - Factorio Version: [e.g. 0.16.51]

**Comment by Cooldude2606** [comment]
This is not a bug, it will only repair ghosts which have been destroied by biters. This is to provent instant blueprint placing.
