### ISSUE TITLE
Admin Permament Map Markers

### ISSUE THREAD

**Issue by Cooldude2606** [explosivegaming/scenario#76]
**Is your feature request related to a problem? Please describe.**
When an admin makes a map marker it should be auto replaced if it is removed by a non-admin to make sure that admin notes and such remain on the map.

**Describe the solution you'd like**
When the tag is removed it is to be remade unless it was removed by an admin; this is done though saving the meesage in a global table that is then read from to reform the marker, similar to warp point markers.

**Describe alternatives you've considered**
There are no other alteratives to this feature.

**Additional context**
N/A

**Comment by tovernaar123** [comment]
this could be nice but sometimes admin just play alot and will mark smt and then no one can remove it might be annoying

**Comment by Cooldude2606** [comment]
Feature has been implemented in #210 and merged into dev branch. Closing issue.
