### ISSUE TITLE
/unjail or promote from /jail does not log

### ISSUE THREAD

**Issue by aldldl** [explosivegaming/scenario#77]
**Is your feature request related to a problem? Please describe.**
It is confusing to follow the reports if the unjails or promotes from jail are not also logged in #reports 

**Describe the solution you'd like**
Any promotion from [Jail] gets logged

**Describe alternatives you've considered**
I have considered being too lazy to write this request, I have also concidered that it may be hard to do without logging/reporting all promotions but I decided both of those were silly and I would write this up.

**Additional context**

**Comment by Cooldude2606** [comment]
Added in v6.
