### ISSUE TITLE
I demoted BADGamerNL and CoolDude by mistake, then for science

### ISSUE THREAD

**Issue by aldldl** [explosivegaming/scenario#78]
**Describe the bug**
I can demote BADGamerNL

**To Reproduce**
1. Go to and do the thing CoolDude knows how to do, then type the other thing he knows how to do.

**Expected behavior**
Mods can not demote cooldude and badgamer

**Screenshots**

**Other information (please complete the following information):**
 - OS: Linux, but also on windows
 - Factorio Version: 0.16.51

**Additional context**
It was really fun and I want to try it again on arty, can you wait to fix it till V4?

**Comment by Cooldude2606** [comment]
The new command system i have added in v4.0 how includes checking of rank and so /jail will no longer work and their are plans to either have full sync with discord or where jail can not be given outside of the command system.
