### ISSUE TITLE
Toggle GUI command

### ISSUE THREAD

**Issue by badgamernl** [explosivegaming/scenario#83]
**Is your feature request related to a problem? Please describe.**
You cannot see detailed info behind top buttons.

**Describe the solution you'd like**
A command (`/toggle-gui`) or some other way to hide GUI buttons obstructing detailed info text.

**Additional context**
If not for this version please think about it for the next modular version before its too hard to implement.
![](https://i.imgur.com/UnekuyJ.png)
^Worse if higher rank but I'm a pleb.

**Comment by Cooldude2606** [comment]
This is now added in v4.0 of the script, this version is soon to be stable and pushed onto the master branch.
![](https://i.imgur.com/lNqhU6P.png)
