### ISSUE TITLE
Verson 4 Bugs (2)

### ISSUE THREAD

**Issue by aldldl** [explosivegaming/scenario#92]
- [ ]  Spawn issue with tones of warps/labels is back in V4
- [ ]  Some really weird stuff with Dark's rank and a jail issue that was happening (see logs)
- [ ]   Dark's inventory got cleared somehow and we dont know why (Does Temp ban clear inventory?)
- [ ]  Can't kill a jailed player
- [ ]  Jailed players in cars/trains etc are unjailable
- [ ]  a few V3.6 items back as issues
--- [ ]  Warp sorts are case sensitive again
- [ ]  Spawn should be spawn once that is fixed for easy /home ing

**Comment by Cooldude2606** [comment]
Issues moved to #85
