### ISSUE TITLE
Spelling error in reports

### ISSUE THREAD

**Issue by DrahcPro** [explosivegaming/scenario#93]
In the reports on discord (and maybe in game) the auto text has a spelling error:

Player
 Jail
There was a player jailed.
Server Details
Server Name: S2 Online Players: 18 Mods Online: 1 Server Time: 5 H 2 M
Player:
xxxxxxxx
By:
xxxxxxxxxx
Reason:
- xxxxxxxxx - 2019 01 24 - **_Vist_** www.explosivegaming.nl to appeal.

please change it 😉

**Comment by Cooldude2606** [comment]
Now Fixed
