### ISSUE TITLE
Timed /Permissions demote if manually b4 time

### ISSUE THREAD

**Issue by aldldl** [explosivegaming/scenario#96]
From Cooldude2606 

> rip the auto move is moving them back down because of lack of play time XD
> will fix some one make bug report for me :stuck_out_tongue:

**Comment by Cooldude2606** [comment]
Fixed in: [5.1.1](https://github.com/explosivegaming/scenario/commit/47a6a3f65eff2b834f51c85ae547dd74237f1f83)
